version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION > /tmp/version.txt
      - LOGIN_COMMAND=$(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - eval $LOGIN_COMMAND

  build:
    commands:
      - echo Building the Docker image...
      - cd nextjs-docker && docker build -t $ECR_REGISTRY_URL:latest .

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $ECR_REGISTRY_URL:latest

