version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION > /tmp/version.txt
      - LOGIN_COMMAND=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
      - docker login -u AWS -p $LOGIN_COMMAND $ECR_REGISTRY_URL
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_REGISTRY_URL:latest .

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $ECR_REGISTRY_URL:latest
      - |
        # Extract ECS service name and cluster name from your existing ECS service ARN
        ECS_SERVICE_NAME="secret-canada-admin-tool-service"
        ECS_CLUSTER_NAME="secret-canada-admin-tool-ecs-cluster"
        
        # Update the ECS service with the latest task definition revision
        aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --force-new-deployment
